# Generated by Django 2.1.2 on 2018-10-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name_plural': 'Commodities'},
        ),
        migrations.AlterField(
            model_name='split',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
